### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by crvilk** [hello-efficiency-inc/raven-reader#374] opened 2019-04-28 02:28 UTC
when I get your source code 
git clone https://github.com/mrgodhani/raven-reader.git
cd raven-reader
yarn install
this will be error
raven-reader\node_modules\@nodert-win10-cu\windows.data.xml.dom: Command failed.
I need your help！！！

**Comment by mrgodhani** [comment] 2019-07-27 22:55
Not able to reproduce closing it.

**Closed by mrgodhani** 2019-07-27 22:55 UTC
