### ISSUE TITLE
Reopen this bug, this is not fixed and is not working in 1.0.11

### ISSUE THREAD

**Issue by sanawu** [hello-efficiency-inc/raven-reader#493] opened 2020-10-30 23:47 UTC
https://github.com/hello-efficiency-inc/raven-reader/issues/491

**Comment by mrgodhani** [comment] 2020-10-31 02:07
Try again should be fixed in 1.0.12

**Closed by mrgodhani** 2020-10-31 02:07 UTC

**Comment by sanawu** [comment] 2020-10-31 09:18
It is not fixed in 1.0.12

**Comment by mrgodhani** [comment] 2020-10-31 11:45
Cannot reproduce. Cannot help much if you don't provide anything.

Following is feedly exported OPML.

[feedly-4a284637-516a-4ca9-8cbf-8889167bc1a8-2020-10-31.opml.zip](https://github.com/hello-efficiency-inc/raven-reader/files/5468983/feedly-4a284637-516a-4ca9-8cbf-8889167bc1a8-2020-10-31.opml.zip)

Working screen:
![Uploading Screen Shot 2020-10-31 at 7.45.01 AM.png…]()
