### ISSUE TITLE
No data loaded from NextInpact.com RSS

### ISSUE THREAD

**Issue by MrChocolatine** [hello-efficiency-inc/raven-reader#473] opened 2020-08-07 08:53 UTC
**Update 2020-08-10**
NextInpact is currently migrating their website to a new version and their RSS feeds seem to work now (but not all). I will update my ticket once their migration is complete.

---

**Describe the bug**

I am trying to subscribe to [NextInpact.com RSS feeds](https://www.nextinpact.com/rss-social), this one for instance:
https://www.nextinpact.com/rss/lebrief.xml

But nothing is loaded, the list of articles and the content view are empty.

**To Reproduce**

1. Open Raven, add a subscription to https://www.nextinpact.com/rss/lebrief.xml
1. No result displayed

**Expected behavior**

Results should be returned.
I already use these RSS feeds from an extension on Firefox and everything works.

**Desktop (please complete the following information):**

 - OS: macOS Catalina v10.15.6
 - Browser Chromium **(I don't understand how it matters since we use your desktop app?)**

**Additional context**

Their XML seem correct, I tested them with https://codebeautify.org/xmlvalidator and https://xmlvalidation.com .

Thank you for your help.

**Comment by mrgodhani** [comment] 2020-08-10 21:46
Above mentioned link does not seem to be available anymore. But trying other RSS from the same page like https://www.inpact-hardware.com/rss/news.xml works fine. Closing this as I am not able to reproduce it.

**Closed by mrgodhani** 2020-08-10 21:46 UTC

**Comment by MrChocolatine** [comment] 2020-08-11 06:48
@mrgodhani Yes my bad, at the time I created this ticket the RSS feeds clearly did not work. But also I did not know they were migrating their website to a newer version, which also broke/messed up their RSS feeds. I guess they will fix everything.
