### ISSUE TITLE
App won't refresh feeds and settings don't get saved

### ISSUE THREAD

**Issue by FriedrichStein** [hello-efficiency-inc/raven-reader#448] opened 2019-08-13 06:23 UTC
I've installed the Raven-Reader on my Computer running Linux Mint Linux Mint 19.2 Cinnamon via the SnapStore. 
The app runs, i can subscribe to a feed and initially the feeds fetches the articles, but after that it won't update the feeds. 
Also when checking for updates an ERROR message appears.

![grafik](https://user-images.githubusercontent.com/53973194/62919544-4c5d1b80-bda3-11e9-93b0-20063e62dec3.png)

Additionaly i can't change the settings. I can alter them, it confirms that the changes are saved, but it hasn't any effect and after a restart they are like in the beginning. 

![grafik](https://user-images.githubusercontent.com/53973194/62919309-942f7300-bda2-11e9-8ef2-5480320c56c6.png)

Unfortunately it doesn't work properly but it looks like a really good app, hope to use it soon. 
Friedrich

**Comment by mrgodhani** [comment] 2019-08-13 12:51
@FriedrichStein What exact settings did you try to change? 

I am aware about that update app thing. It's issue with electron-builder building snap images.

**Comment by FriedrichStein** [comment] 2019-08-15 11:48
I tried to change the update frequency, the appearance and the sorting options. 
It always said that the changes are saved, but it hadn't any effect. 

By the way, a refresh button to update feeds, and a button to save changes would be great :)

**Comment by mrgodhani** [comment] 2019-08-15 12:42
Hm interesting. Testing is mostly done on Ubuntu and I had verified it worked there. Will look into it.

**Comment by mrgodhani** [comment] 2019-08-22 01:07
`Also when checking for updates an ERROR message appears.` Unfortunately that won't work with snaps. Check for Updates works with AppImage. 

Settings seems to be working on Ubuntu. It's difficult to test on so many Linux OSes but I can't reproduce it on Ubuntu.  Closing this for now.

`By the way, a refresh button to update feeds, and a button to save changes would be great :)`
^ Above would be coming in next release.

**Closed by mrgodhani** 2019-08-22 01:07 UTC
